import { useState } from "react";

interface Report {
  name: string;
  description: string;
  lastRun?: string;
  lastRunColor?: "default" | "green" | "orange";
}

const financialReports: Report[] = [
  { name: "Revenue Report", description: "Summary of revenue by date, service, or technician.", lastRun: "2 days ago", lastRunColor: "default" },
  { name: "Profit & Loss Statement", description: "Overview of income, cost of goods sold, and expenses." },
  { name: "Invoice Summary (Accounts Receivable)", description: "Outstanding invoices and aging summary.", lastRun: "3 days ago", lastRunColor: "default" },
  { name: "Expense Report", description: "Track and summarize business expenses." },
  { name: "Sales Tax Report", description: "Sales tax collected and payable summary.", lastRun: "1 week ago", lastRunColor: "default" },
  { name: "Payments Report", description: "Payments received summary by method and date.", lastRun: "1 day ago", lastRunColor: "default" },
];

const estimatesReports: Report[] = [
  { name: "Estimates Report", description: "Summary of estimates by status and date range.", lastRun: "1 week ago", lastRunColor: "default" },
  { name: "Estimate Conversion Report", description: "Conversion of estimates to jobs and revenue.", lastRun: "2 days ago", lastRunColor: "default" },
  { name: "Revenue by Technician", description: "Revenue generated by each technician.", lastRun: "Tomorrow", lastRunColor: "orange" },
];

const jobsReports: Report[] = [
  { name: "Jobs Report", description: "Overview of jobs by status, date, and revenue.", lastRun: "Tomorrow", lastRunColor: "orange" },
  { name: "Job Costing Summary", description: "Job costs, profit margins, and labor analysis.", lastRun: "2 days ago", lastRunColor: "default" },
];

const clientsReports: Report[] = [
  { name: "Client Report", description: "Client details and job / revenue summary.", lastRun: "3 days ago", lastRunColor: "default" },
  { name: "Team Report", description: "Revenue and performance by technician.", lastRun: "Tomorrow", lastRunColor: "orange" },
  { name: "Items Report (Items Usage Report)", description: "Item usage and inventory movement summary.", lastRun: "5 days ago", lastRunColor: "default" },
];

const scheduledReports = [
  { name: "Jobs Report", schedule: "Daily at 7:00 AM", nextRun: "Next run: Tomorrow", nextRunColor: "orange" },
  { name: "Revenue Report", schedule: "Weekly on Monday", nextRun: "Next run: Jun 2, 2025", nextRunColor: "default" },
  { name: "Payments Report", schedule: "Monthly on 1st", nextRun: "Next run: Jun 1, 2025", nextRunColor: "default" },
];

function LastRunBadge({ label, color }: { label: string; color?: "default" | "green" | "orange" }) {
  const cls =
    color === "orange"
      ? "text-[#D97706]"
      : color === "green"
      ? "text-[#16A34A]"
      : "text-[#546478]";
  return <span className={`text-xs font-medium ${cls} whitespace-nowrap`}>{label}</span>;
}

function ReportRow({ report }: { report: Report }) {
  return (
    <div className="flex items-center justify-between py-3 border-b border-[#F3F4F6] last:border-0 gap-4">
      <div className="flex-1 min-w-0">
        <div className="text-sm font-semibold text-[#1A2332] truncate">{report.name}</div>
        <div className="text-xs text-[#546478] truncate">{report.description}</div>
      </div>
      <div className="flex items-center gap-3 shrink-0">
        {report.lastRun && <LastRunBadge label={report.lastRun} color={report.lastRunColor} />}
        <button className="text-[#546478] hover:text-[#1A2332] transition-colors" title="Preview">
          <span className="material-icons" style={{ fontSize: 15 }}>visibility</span>
        </button>
        <button className="text-[#546478] hover:text-[#1A2332] transition-colors" title="Download">
          <span className="material-icons" style={{ fontSize: 15 }}>file_download</span>
        </button>
      </div>
    </div>
  );
}

function SectionCard({ icon, title, reports }: { icon: string; title: string; reports: Report[] }) {
  return (
    <div className="mb-5">
      <div className="flex items-center gap-2 mb-2">
        <span className="material-icons text-[#4A6FA5]" style={{ fontSize: 16 }}>{icon}</span>
        <span className="text-sm font-bold text-[#1A2332]">{title}</span>
      </div>
      <div className="bg-white rounded-xl border border-[#E5E7EB] px-4 shadow-[0_1px_2px_rgba(0,0,0,0.05)]">
        {reports.map((r) => (
          <ReportRow key={r.name} report={r} />
        ))}
      </div>
    </div>
  );
}

export function Reports() {
  const [activeTab, setActiveTab] = useState("reports");
  const [search, setSearch] = useState("");

  return (
    <div className="p-8 min-h-screen bg-[#F9FAFB]">
      {/* Header */}
      <div className="flex items-start justify-between mb-5">
        <div>
          <h1 className="text-2xl font-bold text-[#1A2332]">Omega Home Services Business Insights</h1>
          <p className="text-sm text-[#546478] mt-0.5">Generate, schedule, and export business reports.</p>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          <button className="flex items-center gap-1.5 text-sm font-medium text-[#1A2332] bg-white border border-[#E5E7EB] rounded-lg px-3 py-2 shadow-sm hover:bg-[#F3F4F6] transition-colors">
            <span className="material-icons text-[#546478]" style={{ fontSize: 15 }}>calendar_today</span>
            This Month
            <span className="material-icons text-[#546478]" style={{ fontSize: 14 }}>keyboard_arrow_down</span>
          </button>
          <button className="flex items-center gap-1.5 text-sm font-semibold text-white bg-[#4A6FA5] rounded-lg px-4 py-2 shadow-sm hover:bg-[#3d5a85] transition-colors">
            <span className="material-icons" style={{ fontSize: 15 }}>bar_chart</span>
            Generate Report
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex items-center gap-1 mb-5 border-b border-[#E5E7EB]">
        {[
          { id: "all", label: "All Business" },
          { id: "sales", label: "Sales Performance" },
          { id: "financial", label: "Financial Performance" },
          { id: "reports", label: "Reports" },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`px-4 py-2.5 text-sm font-medium rounded-t-md transition-colors border-b-2 -mb-px ${
              activeTab === tab.id
                ? "text-white bg-[#1A2332] border-[#1A2332]"
                : "text-[#546478] border-transparent hover:text-[#1A2332] hover:border-[#E5E7EB]"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Stat Cards */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <div className="bg-white rounded-xl border border-[#E5E7EB] px-5 py-4 flex items-center justify-between shadow-[0_1px_2px_rgba(0,0,0,0.05)]">
          <div>
            <div className="text-2xl font-bold text-[#1A2332]">14</div>
            <div className="text-xs text-[#546478] mt-0.5">Reports available</div>
          </div>
          <div className="w-10 h-10 bg-[#EFF6FF] rounded-xl flex items-center justify-center">
            <span className="material-icons text-[#4A6FA5]" style={{ fontSize: 20 }}>description</span>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-[#E5E7EB] px-5 py-4 flex items-center justify-between shadow-[0_1px_2px_rgba(0,0,0,0.05)]">
          <div>
            <div className="text-2xl font-bold text-[#1A2332]">2 days ago</div>
            <div className="text-xs text-[#546478] mt-0.5">Last export</div>
            <div className="text-xs font-semibold text-[#1A2332] mt-0.5">Revenue Report</div>
          </div>
          <div className="w-10 h-10 bg-[#F0FDF4] rounded-xl flex items-center justify-center">
            <span className="material-icons text-[#16A34A]" style={{ fontSize: 20 }}>file_download</span>
          </div>
        </div>
        <div className="bg-white rounded-xl border border-[#E5E7EB] px-5 py-4 flex items-center justify-between shadow-[0_1px_2px_rgba(0,0,0,0.05)]">
          <div>
            <div className="text-2xl font-bold text-[#1A2332]">3</div>
            <div className="text-xs text-[#546478] mt-0.5">Scheduled reports</div>
            <div className="text-xs font-semibold text-[#1A2332] mt-0.5">
              Next: Jobs Report <span className="text-[#546478] font-normal">(Tomorrow)</span>
            </div>
          </div>
          <div className="w-10 h-10 bg-[#FFFBEB] rounded-xl flex items-center justify-center">
            <span className="material-icons text-[#D97706]" style={{ fontSize: 20 }}>schedule</span>
          </div>
        </div>
      </div>

      {/* Search + Filter bar */}
      <div className="flex items-center gap-3 mb-5">
        <div className="relative flex-1 max-w-sm">
          <span className="material-icons absolute left-3 top-1/2 -translate-y-1/2 text-[#9CA3AF]" style={{ fontSize: 15 }}>search</span>
          <input
            type="text"
            placeholder="Search reports..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full pl-8 pr-4 py-2 text-sm bg-white border border-[#E5E7EB] rounded-lg text-[#1A2332] placeholder-[#9CA3AF] focus:outline-none focus:ring-2 focus:ring-[#4A6FA5]/30"
          />
        </div>
        <div className="ml-auto flex items-center gap-2">
          <button className="flex items-center gap-1.5 text-sm text-[#1A2332] bg-white border border-[#E5E7EB] rounded-lg px-3 py-2 hover:bg-[#F3F4F6] transition-colors">
            All Categories
            <span className="material-icons text-[#546478]" style={{ fontSize: 14 }}>keyboard_arrow_down</span>
          </button>
        </div>
      </div>

      {/* Two-column layout */}
      <div className="grid grid-cols-2 gap-6">
        {/* Left column */}
        <div>
          <SectionCard icon="bar_chart" title="Financial / Business" reports={financialReports} />
          <SectionCard icon="description" title="Estimates" reports={estimatesReports} />
        </div>

        {/* Right column */}
        <div>
          <SectionCard icon="work" title="Jobs" reports={jobsReports} />
          <SectionCard icon="group" title="Clients / Team / Items" reports={clientsReports} />

          {/* Recent Scheduled Reports */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <span className="material-icons text-[#4A6FA5]" style={{ fontSize: 16 }}>schedule</span>
                <span className="text-sm font-bold text-[#1A2332]">Recent Scheduled Reports</span>
              </div>
              <button className="text-sm font-medium text-[#4A6FA5] hover:underline">View all</button>
            </div>
            <div className="bg-white rounded-xl border border-[#E5E7EB] px-4 shadow-[0_1px_2px_rgba(0,0,0,0.05)]">
              {scheduledReports.map((r, i) => (
                <div
                  key={r.name + i}
                  className="flex items-center justify-between py-3 border-b border-[#F3F4F6] last:border-0 gap-4"
                >
                  <div className="flex-1 min-w-0">
                    <div className="text-sm font-semibold text-[#1A2332] truncate">{r.name}</div>
                    <div className="text-xs text-[#546478] truncate">{r.schedule}</div>
                  </div>
                  <div className="flex items-center gap-3 shrink-0">
                    <span className={`text-xs font-medium ${r.nextRunColor === "orange" ? "text-[#D97706]" : "text-[#546478]"}`}>
                      {r.nextRun}
                    </span>
                    <button className="text-[#546478] hover:text-[#1A2332] transition-colors">
                      <span className="material-icons" style={{ fontSize: 16 }}>more_horiz</span>
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Footer banner */}
      <div className="mt-6 flex items-center justify-between bg-white border border-[#E5E7EB] rounded-xl px-5 py-3 shadow-[0_1px_2px_rgba(0,0,0,0.05)]">
        <div className="flex items-center gap-2 text-sm text-[#546478]">
          <span className="material-icons text-[#4A6FA5]" style={{ fontSize: 16 }}>info</span>
          Need a custom report? Contact support or let us know what you'd like to see.
        </div>
        <button className="flex items-center gap-1 text-sm font-medium text-[#4A6FA5] hover:underline">
          Contact Support
          <span className="material-icons" style={{ fontSize: 14 }}>open_in_new</span>
        </button>
      </div>
    </div>
  );
}
